"""Obsidian vault export — reproduces the EXACT layout/format of the user's
existing vault (the original generator is no longer in the repo, so this is
replicated from the real artifacts):

  Meetings/<stem>/<stem>_summary.md     (frontmatter + body + footer)
  Meetings/<stem>/<stem>_analysis.md    (rich emoji/table report, all features)
  Meetings/_index/By Date.md            (## <date> + - [[<stem>/<stem>_summary|<stem>]] - <topic>)
  Meetings/_queries/{Action Items,By Person,By Topic,Recent Meetings}.md  (static Dataview)
  People/<name>.md, Topics/<topic>.md   (vault root; one link-line per meeting)

Files are named by the input stem (matching transcripts/). Versions append
`_vN` for v2+. The analysis report is rendered HERE (not via the unified
exporter) to match the established format exactly.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path

# Relative, like every other module here: the absolute form only resolved
# when desktop/ happened to be on sys.path and broke the moment the package
# was imported as ``desktop.app...`` (which is how the server imports these
# shared adapters).
from .exporter import app_version

APP_VERSION = app_version()   # single source of truth: package.json
FOOTER = f"*Generated by Meeting Summarizer v{APP_VERSION}*"

PRIORITY_RU = {"high": "ВЫСОКИЙ", "medium": "СРЕДНИЙ", "low": "НИЗКИЙ"}
PRIORITY_EMOJI = {"high": "🔴", "medium": "🟡", "low": "🟢"}
STATUS_EMOJI = {"identified": "🆕", "in-progress": "⏳", "resolved": "✅"}
IMPACT_EMOJI = {"high": "⚡", "medium": "⚖️", "low": "📉"}
OVERALL_RU = {"positive": "Позитивная", "neutral": "Нейтральная", "negative": "Негативная"}

_QUERIES = {
    "Action Items.md": """# All Action Items

```dataview
TABLE WITHOUT ID
  file.link as "Meeting",
  file.ctime as "Date"
FROM "Meetings"
WHERE file.name != "_index" AND file.name != "_queries"
SORT file.ctime DESC
```

> Note: This query shows meetings. Open individual meeting analysis files to see action items.
""",
    "By Person.md": """# Meetings by Person

```dataview
TABLE
  rows.file.link as "Meetings"
FROM "People"
FLATTEN file.outlinks as meeting
WHERE contains(string(meeting), "Meetings/")
GROUP BY file.link
```
""",
    "By Topic.md": """# Meetings by Topic

```dataview
TABLE
  rows.file.link as "Meetings"
FROM "Topics"
FLATTEN file.outlinks as meeting
WHERE contains(string(meeting), "Meetings/")
GROUP BY file.link
```
""",
    "Recent Meetings.md": """# Recent Meetings

```dataview
TABLE
  file.ctime as "Date",
  file.size as "Size"
FROM "Meetings"
WHERE file.name != "_index" AND file.name != "_queries"
SORT file.ctime DESC
LIMIT 10
```
""",
}


def _date_from_stem(stem: str) -> str:
    """The meeting's date from its file name, today's date when it has none.

    Delegates to the single parser in ``media`` — a private copy here only knew
    ``YYYY-MM-DD`` and read nothing out of '17.08.2026 15-33.mkv'."""
    from .media import meeting_datetime_from_name
    date_iso, _ = meeting_datetime_from_name(stem)
    return date_iso or datetime.now().strftime("%Y-%m-%d")


def _safe(name: str) -> str:
    for ch in '/\\:*?"<>|':
        name = name.replace(ch, "-")
    return name.strip() or "Unnamed"


def _versioned(base: str, version: int) -> str:
    return base if (version or 1) <= 1 else f"{base}_v{version}"


def _word_count_text(transcript_text: str) -> str:
    if not transcript_text:
        return "N/A"
    n = len(transcript_text.split())
    return f"{n:,}".replace(",", " ")


def build_summary_md(summary_text: str, *, stem: str, date_str: str, duration: str) -> str:
    fm = ("---\n"
          "type: meeting-summary\n"
          f"date: {date_str}\n"
          f"title: {stem}\n"
          "tags: [meeting, summary]\n"
          f"app_version: {APP_VERSION}\n"
          "---\n")
    head = f"\n# {stem}\n\n**Date:** {date_str}\n**Duration:** {duration or 'N/A'}\n\n---\n\n"
    body = (summary_text or "").strip()
    return f"{fm}{head}{body}\n\n\n---\n\n{FOOTER}"


def build_transcript_md(transcript_text: str, *, stem: str, date_str: str,
                        duration: str) -> str:
    """The transcript as its own note.

    The vault only ever held summary and analysis notes, so choosing "Transcript"
    and pressing the Obsidian button silently produced a summary note instead.
    """
    fm = ("---\n"
          "type: meeting-transcript\n"
          f"date: {date_str}\n"
          f"title: {stem}\n"
          "tags: [meeting, transcript]\n"
          f"app_version: {APP_VERSION}\n"
          "---\n")
    head = (f"\n# {stem}\n\n**Date:** {date_str}\n"
            f"**Duration:** {duration or 'N/A'}\n\n---\n\n")
    body = (transcript_text or "").strip()
    return f"{fm}{head}{body}\n\n\n---\n\n{FOOTER}"


def _first_topic(summary_text: str) -> str:
    for line in (summary_text or "").split("\n"):
        s = line.strip()
        if s.startswith("## "):
            return s
    return ""


def update_index(vault: Path, date_str: str, link_base: str, stem: str, summary_text: str) -> None:
    folder = vault / "Meetings" / "_index"
    folder.mkdir(parents=True, exist_ok=True)
    index = folder / "By Date.md"
    content = index.read_text(encoding="utf-8") if index.exists() else ""
    entry = f"- [[{link_base}|{stem}]] - {_first_topic(summary_text)}".rstrip(" -")
    if entry in content:
        return
    header = f"## {date_str}"
    if header not in content:
        content += f"\n{header}\n\n{entry}\n"
    else:
        content = content.replace(f"{header}\n", f"{header}\n\n{entry}\n", 1)
    index.write_text(content.lstrip("\n"), encoding="utf-8")


def write_queries(vault: Path) -> None:
    folder = vault / "Meetings" / "_queries"
    folder.mkdir(parents=True, exist_ok=True)
    for name, body in _QUERIES.items():
        path = folder / name
        if not path.exists():
            path.write_text(body, encoding="utf-8")


def build_analysis_md(analysis, *, stem: str, duration: str, participants: str,
                      word_count_text: str) -> str:
    a = analysis or {}
    out = ["# 📊 Meeting Analysis", "", f"**File:** {stem}",
           f"**Generated:** {datetime.now().strftime('%d.%m.%Y, %H:%M:%S')}", "", "---", ""]

    ch = a.get("characteristics") or {}
    kt = ch.get("keyTopics") or []
    out += ["## 📋 Характеристики встречи", "", "| | |", "|---|---|",
            f"| ⏱️ **Длительность** | {duration or 'N/A'} |",
            f"| 👥 **Участники** | {participants or 'N/A'} |",
            f"| 📝 **Количество слов** | {word_count_text} |",
            f"| 🔑 **Ключевые темы** | {', '.join(str(x) for x in kt) if kt else 'N/A'} |", ""]

    ai = a.get("actionItems") or []
    if ai:
        out += ["## ✅ Задачи и Action Items", ""]
        for i, it in enumerate(ai, 1):
            pr = (it.get("priority") or "").lower()
            out += [f"### {i}. {it.get('task', '')}", "",
                    f"- {PRIORITY_EMOJI.get(pr, '⚪')} **Priority:** "
                    f"{PRIORITY_RU.get(pr, it.get('priority', ''))}",
                    f"- 👤 **Assignee:** {it.get('assignee') or 'Не назначен'}",
                    f"- 📅 **Deadline:** {it.get('deadline') or 'Не указан'}", ""]

    s = a.get("sentiment")
    if isinstance(s, dict) and s:
        out += ["## 😊 Анализ тональности", "", "| Metric | Value |", "|---|---|"]
        if s.get("overall"):
            out.append(f"| **Встреча** | {OVERALL_RU.get(s['overall'], s['overall'])} |")
        if s.get("engagement"):
            out.append(f"| **Уровень вовлеченности участников** | {s['engagement']}% |")
        if "hasConflict" in s:
            out.append(f"| **Наличие конфликтов** | {'ДА' if s['hasConflict'] else 'НЕТ'} |")
        if s.get("interruptionIndex") is not None:
            out.append(f"| **Индекс прерываний** | {s['interruptionIndex']}/100 |")
        if s.get("emotionalBalance") is not None:
            out.append(f"| **Эмоциональный баланс** | {s['emotionalBalance']}/100 |")
        if s.get("empathyIndex") is not None:
            out.append(f"| **Индекс эмпатии** | {s['empathyIndex']}/100 |")
        if s.get("speechSpeedVariability"):
            out.append(f"| **Вариативность скорости речи** | {s['speechSpeedVariability']} |")
        if s.get("questionsToAnswersRatio") is not None:
            out.append(f"| **Соотношение вопросов к ответам** | {s['questionsToAnswersRatio']} |")
        out.append("")
        if s.get("emotions"):
            out += [f"**Эмоции участников:** {', '.join(str(e) for e in s['emotions'])}", ""]
        if s.get("description"):
            out += [s["description"], ""]
        dd = s.get("dominanceDistribution")
        if isinstance(dd, dict) and dd:
            out += ["### Распределение доминирования", ""]
            out += [f"- **{k}:** {v}%" for k, v in dd.items()]
            out.append("")

    c = a.get("category")
    if isinstance(c, dict) and c:
        out += ["## 📂 Категория встречи", ""]
        if c.get("category"):
            out += [f"**{c['category']}**", ""]
        if c.get("tags"):
            out += [f"**Tags:** {', '.join(f'`{t}`' for t in c['tags'])}", ""]
        if c.get("description"):
            out += [c["description"], ""]

    r = a.get("risks") or []
    if r:
        out += ["## 🔴 Риски и блокеры", ""]
        for i, it in enumerate(r, 1):
            sev = (it.get("severity") or "").lower()
            st = (it.get("status") or "").lower()
            out += [f"### {i}. {it.get('description', '')}", "",
                    f"- {PRIORITY_EMOJI.get(sev, '⚪')} **Severity:** {it.get('severity', '')}",
                    f"- {STATUS_EMOJI.get(st, '🆕')} **Status:** {it.get('status', '')}",
                    f"- **Impact:** {it.get('impact', '')}", ""]

    q = a.get("quotes") or []
    if q:
        out += ["## 💬 Ключевые цитаты", ""]
        for i, it in enumerate(q, 1):
            out += [f'### {i}. "{it.get("text", "")}"', ""]
            if it.get("speaker"):
                out.append(f"- **Speaker:** {it['speaker']}")
            if it.get("context"):
                out.append(f"- **Context:** {it['context']}")
            out.append("")

    t = a.get("technologies") or []
    if t:
        out += ["## 💻 Технологии и системы", ""]
        groups, order = {}, []
        for it in t:
            cat = it.get("category") or "other"
            if cat not in groups:
                groups[cat] = []
                order.append(cat)
            groups[cat].append(it)
        for cat in order:
            out += [f"### {cat}", ""]
            out += [f"- **{it.get('name', '')}**: {it.get('context', '')}" for it in groups[cat]]
            out.append("")

    qq = a.get("questions") or []
    if qq:
        out += ["## ❓ Нерешенные вопросы", ""]
        for i, it in enumerate(qq, 1):
            pr = (it.get("priority") or "").lower()
            out += [f"### {i}. {it.get('question', '')}", "",
                    f"- {PRIORITY_EMOJI.get(pr, '⚪')} **Priority:** {it.get('priority', '')}"]
            if it.get("category"):
                out.append(f"- **Category:** {it['category']}")
            if it.get("owner"):
                out.append(f"- **Owner:** {it['owner']}")
            out.append("")

    rec = a.get("recommendations") or []
    if rec:
        out += ["## 💡 Рекомендации", ""]
        for i, it in enumerate(rec, 1):
            pr = (it.get("priority") or "").lower()
            im = (it.get("impact") or "").lower()
            out += [f"### {i}. {it.get('recommendation', '')}", "",
                    f"- {PRIORITY_EMOJI.get(pr, '⚪')} **Priority:** {it.get('priority', '')}",
                    f"- {IMPACT_EMOJI.get(im, '⚖️')} **Impact:** {it.get('impact', '')}"]
            if it.get("category"):
                out.append(f"- **Category:** {it['category']}")
            out.append("")

    fq = a.get("followupQuestions") or []
    if fq:
        out += ["## 🔄 Вопросы к следующей встрече", ""]
        for i, it in enumerate(fq, 1):
            pr = (it.get("priority") or "").lower()
            out += [f"### {i}. {it.get('question', '')}", "",
                    f"- {PRIORITY_EMOJI.get(pr, '⚪')} **Priority:** {it.get('priority', '')}"]
            if it.get("category"):
                out.append(f"- **Category:** {it['category']}")
            if it.get("context"):
                out.append(f"- **Context:** {it['context']}")
            out.append("")

    fp = a.get("formalProtocol")
    if isinstance(fp, dict) and fp:
        out += ["## 📜 Формальный протокол", ""]
        for label, key in (("Номер", "protocolNumber"), ("Дата", "date"), ("Время", "time"),
                           ("Место", "location"), ("Председатель", "chairman"),
                           ("Секретарь", "secretary"), ("Следующая встреча", "nextMeeting")):
            if fp.get(key):
                out.append(f"- **{label}:** {fp[key]}")
        out.append("")
        if fp.get("participants"):
            out += ["**Участники:** " + ", ".join(str(x) for x in fp["participants"]), ""]
        if fp.get("agenda"):
            out.append("**Повестка:**")
            out += [f"{i}. {x}" for i, x in enumerate(fp["agenda"], 1)]
            out.append("")
        if fp.get("decisions"):
            out += ["### Решения", ""]
            for d in fp["decisions"]:
                out.append(f"**{d.get('number', '')}.** {d.get('text', '')}")
                if d.get("votingResult"):
                    out.append(f"- Голосование: {d['votingResult']}")
                out.append("")
        if fp.get("actionItems"):
            out += ["### Задачи протокола", ""]
            out += [f"{i}. {it.get('task', '')} — {it.get('assignee', '')} "
                    f"({it.get('deadline', '')})" for i, it in enumerate(fp["actionItems"], 1)]
            out.append("")
        if fp.get("protocolText"):
            out += [fp["protocolText"], ""]

    out += ["---", "", FOOTER]
    return "\n".join(out)


def _append_link_line(path: Path, line: str) -> None:
    content = path.read_text(encoding="utf-8") if path.exists() else ""
    if line in content:
        return
    path.write_text((content.rstrip("\n") + "\n" + line + "\n").lstrip("\n"), encoding="utf-8")


def write_people(vault: Path, analysis: dict, date_str: str, link_base: str, stem: str) -> None:
    s = (analysis or {}).get("sentiment") or {}
    dd = s.get("dominanceDistribution") if isinstance(s, dict) else None
    if not isinstance(dd, dict) or not dd:
        return
    folder = vault / "People"
    folder.mkdir(parents=True, exist_ok=True)
    for name, pct in dd.items():
        line = f"- {date_str}: [[{link_base}|{stem}]] ({pct}% speaking time)"
        _append_link_line(folder / f"{_safe(str(name))}.md", line)


def write_topics(vault: Path, analysis: dict, date_str: str, link_base: str, stem: str) -> None:
    a = analysis or {}
    topics = list((a.get("characteristics") or {}).get("keyTopics") or [])
    cat = a.get("category")
    if isinstance(cat, dict):
        topics += list(cat.get("tags") or [])
    topics = [t for t in dict.fromkeys(t for t in topics if t)]
    if not topics:
        return
    folder = vault / "Topics"
    folder.mkdir(parents=True, exist_ok=True)
    for topic in topics:
        _append_link_line(folder / f"{_safe(str(topic))}.md",
                          f"- {date_str}: [[{link_base}|{stem}]]")


def export_to_obsidian(vault_path, *, stem: str, video_name: str, summary_text: str,
                       analysis: dict, settings: dict, duration: str = "",
                       summary_version: int = 1, analysis_version: int = 1,
                       transcript_text: str = "", language: str = "ru",
                       kinds: "tuple | None" = None) -> dict:
    """Write the requested notes into `Meetings/<stem>/`, plus gated index /
    queries / People / Topics. Returns {vault, summary, analysis, transcript}.

    ``kinds`` selects what to write ("summary", "analysis", "raw"); the default
    keeps the historic behaviour of writing summary + analysis together.
    """
    vault = Path(vault_path)
    if not str(vault_path).strip() or not vault.exists():
        raise FileNotFoundError(f"Obsidian vault not found: {vault_path}")
    date_str = _date_from_stem(stem)
    folder = vault / "Meetings" / stem
    folder.mkdir(parents=True, exist_ok=True)
    result = {"vault": str(vault), "summary": None, "analysis": None,
              "transcript": None}
    wanted = set(kinds or ("summary", "analysis"))

    sum_name = _versioned(f"{stem}_summary", summary_version)
    link_base = f"{stem}/{sum_name}"
    if "summary" in wanted:
        sum_path = folder / f"{sum_name}.md"
        sum_path.write_text(
            build_summary_md(summary_text, stem=stem, date_str=date_str, duration=duration),
            encoding="utf-8")
        result["summary"] = str(sum_path)

    if "raw" in wanted:
        tr_path = folder / f"{stem}_transcript.md"
        tr_path.write_text(
            build_transcript_md(transcript_text, stem=stem, date_str=date_str,
                                duration=duration), encoding="utf-8")
        result["transcript"] = str(tr_path)

    if "analysis" in wanted and isinstance(analysis, dict) and analysis:
        an_name = _versioned(f"{stem}_analysis", analysis_version)
        an_path = folder / f"{an_name}.md"
        an_path.write_text(
            build_analysis_md(analysis, stem=stem, duration=duration, participants="N/A",
                              word_count_text=_word_count_text(transcript_text)),
            encoding="utf-8")
        result["analysis"] = str(an_path)

    if settings.get("updateMeetingIndex"):
        update_index(vault, date_str, link_base, stem, summary_text)
    if settings.get("createDataviewQueries"):
        write_queries(vault)
    if settings.get("createPeopleNotes"):
        write_people(vault, analysis, date_str, link_base, stem)
    if settings.get("createTopicNotes"):
        write_topics(vault, analysis, date_str, link_base, stem)
    return result
